name: 'Surge PR Preview'
description: 'Preview website in surge.sh for every pull request'
author: 'afc163'
inputs:
  milliseconds: # change this
    required: true
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node12'
  main: 'dist/index.js'
